{{- if .Values.global.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccount.name }}
  labels:
    {{.Values.web.labels | toYaml | nindent 4 }}
{{- end -}}