pipeline:
  name: New Pipeline
  identifier: New_Pipeline
  projectIdentifier: GitX_V2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: New Stage
        identifier: New_Stage
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: service
          environment:
            environmentRef: dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra_def
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Step
                  identifier: Shell_Step
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello world"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
