apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-svc
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "tenant00000-ingress-k8s.dev.aptivconnect.app"
    service.beta/load-balancer-tcp-idle-timeout: "1234567894"
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}