# Local splunk configurations
splunk:
  # Configurations for HEC (HTTP Event Collector)
  hec: 
    # host is required and should be provided by user
    host: "prd-p-gbleo.splunkcloud.com"
    # token is required and should be provided by user
    token: "${secrets.getValue("splunk_hec_delegate_logs")}"