harnessApiVersion: '1.0'
type: GOVERNANCE_CONFIG
disableAllDeployments: false
timeRangeBasedFreezeConfigs:
- type: TIME_RANGE_BASED_FREEZE_CONFIG
  appSelections:
  - apps:
    - Fundamentals Harness training
    envSelection:
    - environments:
      - Pedro Production
      filterType: CUSTOM
    filterType: CUSTOM
    serviceSelection:
    - filterType: CUSTOM
      services:
      - DummyService
  applicable: false
  description: description
  name: create-api-example
  timeRange:
    duration: '604800000'
    durationBased: true
    from: '1650286664143'
    timeZone: Asia/Calcutta
    to: '1650891464143'
  userGroupSelection:
    filterType: CUSTOM
    userGroupNames:
    - Account Administrator
  userGroups:
  - Account Administrator
