pipeline:
    name: approval-test2
    identifier: approvaltest2
    projectIdentifier: Rolling_Lab
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: t2
              identifier: t2
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approval
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.DOE.HRNS.AutomationEngineer
                                    approverInputs: []
              tags: {}
