pipeline:
    name: Lab 30673
    identifier: Lab_30673
    projectIdentifier: Rolling_Lab
    orgIdentifier: default
    tags: {}
    stages:
        - parallel:
              - stage:
                    name: Sample Stage
                    identifier: Sample_Stage
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: Basic_Service
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: Basic_Infra
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: account.CCM_Connector
                                    namespace: <+env.name>
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Basic Shell
                                      identifier: Basic_Shell
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: |-
                                                      echo "Hello World"

                                                      echo "<+infra.namespace>"
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                          delegateSelectors:
                                              - account-delegate-new
                                      timeout: 10m
                                      failureStrategies: []
                            rollbackSteps:
                                - step:
                                      name: Rollback Rollout Deployment
                                      identifier: rollbackRolloutDeployment
                                      type: K8sRollingRollback
                                      timeout: 10m
                                      spec: {}
                        serviceDependencies: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
                    delegateSelectors:
                        - account-delegate-new
              - stage:
                    name: tst
                    identifier: tst
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            useFromStage:
                                stage: Sample_Stage
                        infrastructure:
                            environmentRef: Basic_Infra
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: Test_K8s_Connector
                                    namespace: seqwe
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: dfsf
                                      identifier: dfsf
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo hello world
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps:
                                - step:
                                      name: Rollback Rollout Deployment
                                      identifier: rollbackRolloutDeployment
                                      type: K8sRollingRollback
                                      timeout: 10m
                                      spec: {}
                        serviceDependencies: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
    variables:
        - name: aaaaa
          type: String
          default: aaaaaaaaaaaaaa
          value: <+input>
