pipeline:
  allowStageExecutions: false
  projectIdentifier: Rolling_Lab
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Rolling Deploy
        identifier: Rolling_Deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Basic_Service
            serviceDefinition:
              type: Kubernetes
              spec:
                variables: []
                manifests:
                  - manifest:
                      identifier: BasicManifest
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /templates
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                        skipResourceVersioning: false
                  - manifest:
                      identifier: Values
                      type: Values
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /values.yaml
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                artifacts:
                  primary:
                    spec:
                      connectorRef: account.harnessImage
                      imagePath: library/nginx
                      tag: <+stage.variables.test>
                    type: DockerRegistry
          infrastructure:
            environmentRef: Basic_Infra
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: account.Testaaa
                namespace: pedro
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Configure Delegate based on the environment
                  identifier: Configure_Delegate_based_on_the_environment
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: branch='test' if [ $branch = 'test'] echo "hello" fi
                    environmentVariables: []
                    outputVariables:
                      - name: DELEGATE_NAME
                        type: String
                        value: DELEGATE
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    skipDryRun: false
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: test
            type: String
            default: dev
            description: ""
            value: <+input>.allowedValues(dev,staging,prod)
        when:
          pipelineStatus: Success
  notificationRules:
    - name: Test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account.Test_User_Group
          recipients: []
      enabled: true
  flowControl:
    barriers: []
  variables: []
  identifier: T27885_Clone
  name: T32997 - get secret
