pipeline:
  allowStageExecutions: false
  projectIdentifier: Rolling_Lab
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Rolling Deploy
        identifier: Rolling_Deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Basic_Service
            serviceDefinition:
              type: Kubernetes
              spec:
                variables:
                  - name: test
                    type: String
                    value: <+input>
                manifests:
                  - manifest:
                      identifier: BasicManifest
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /templates
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                        skipResourceVersioning: false
                  - manifest:
                      identifier: Values
                      type: Values
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /values.yaml
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                artifacts:
                  primary:
                    spec:
                      connectorRef: <+input>
                      imagePath: <+input>
                      tag: <+input>
                    type: DockerRegistry
          infrastructure:
            environmentRef: Basic_Infra
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: account.CCM_Connector
                namespace: test
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Get Secret Name
                  identifier: Prepare_Secret
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: SECRET_NAME=$(echo "account.original<+project.name>crypto<+env.name>")
                    environmentVariables: []
                    outputVariables:
                      - name: SECRET_NAME
                        type: String
                        value: SECRET_NAME
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.variables.use_cache> == "true"
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    skipDryRun: false
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: custom_tag
            type: String
            value: <+input>
        when:
          pipelineStatus: Success
  notificationRules:
    - name: Test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account.Test_User_Group
          recipients: []
      enabled: true
  flowControl:
    barriers: []
  variables:
    - name: a
      type: String
      default: aaaaaa
      value: <+input>
    - name: use_cache
      type: String
      description: ""
      value: <+input>
  identifier: T27885_Clone
  name: T32997 - get secret
