pipeline:
  allowStageExecutions: false
  projectIdentifier: Rolling_Lab
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Rolling Deploy
        identifier: Rolling_Deploy
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: Basic_Service
            serviceDefinition:
              type: Kubernetes
              spec:
                variables:
                  - name: test
                    type: String
                    value: <+input>
                manifests:
                  - manifest:
                      identifier: BasicManifest
                      type: K8sManifest
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /templates
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                        skipResourceVersioning: false
                  - manifest:
                      identifier: Values
                      type: Values
                      spec:
                        store:
                          type: Github
                          spec:
                            connectorRef: account.tres
                            gitFetchType: Branch
                            paths:
                              - /values.yaml
                            repoName: pedrokuhn/basic-service-manifest
                            branch: labBO
                artifacts:
                  primary:
                    spec:
                      connectorRef: <+input>
                      imagePath: <+input>
                      tag: <+input>
                    type: DockerRegistry
          infrastructure:
            environmentRef: Basic_Infra
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: account.Testaaa
                namespace: pedro
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Configure Delegate based on the environment
                  identifier: Configure_Delegate_based_on_the_environment
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          case <+stage.variables.test> in

                            dev)
                              echo -n "Dev environemnt is using delegates from: pedrocs"
                              DELEGATE="pedrocs"
                              ;;

                            staging | Moldova)
                              echo -n "Dev environemnt is using delegates from: pedrocse-staging"
                              DELEGATE="pedrocse-staging"
                              ;;

                            prod | "San Marino" | Switzerland | "Vatican City")
                              echo -n "Dev environemnt is using delegates from: pedrocse-prod"
                              DELEGATE="pedrocse-prod"
                              ;;

                            *)
                              echo -n "<+stage.variables.test> is not a valid environment"
                              exit 1
                              ;;
                          esac
                    environmentVariables: []
                    outputVariables:
                      - name: DELEGATE_NAME
                        type: String
                        value: DELEGATE
                  timeout: 10m
              - step:
                  type: K8sRollingDeploy
                  name: Rolling Deployment
                  identifier: Rolling_Deployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    delegateSelectors:
                      - <+steps.Configure_Delegate_based_on_the_environment.output.outputVariables.DELEGATE_NAME>
                  timeout: 10m
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    skipDryRun: false
          serviceDependencies: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        variables:
          - name: test
            type: String
            default: dev
            description: ""
            value: <+input>.allowedValues(dev,staging,prod)
        when:
          pipelineStatus: Success
  notificationRules:
    - name: Test
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account.Test_User_Group
          recipients: []
      enabled: true
  flowControl:
    barriers: []
  variables: []
  identifier: T27885_Clone
  name: T32997 - get secret
