apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.name}}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{.Values.awsaccountid}}:role/{{.Values.env.config.enviroment}}-{{.Values.name}}
---
#Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
rules:
  - apiGroups:
      - apps
    resourceNames:
      - {{.Values.name}}-deployment-blue
      - {{.Values.name}}-deployment-green
    resources:
      - deployments
    verbs:
      - patch
      - update
      - restart
  - apiGroups:
      - '*'
    resources:
      - namespaces
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
subjects:
  - kind: ServiceAccount
    name: {{.Values.name}}
    namespace: {{.Values.namespace}}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role
  name: {{.Values.name}}
  apiGroup: rbac.authorization.k8s.io