apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    harness.io/name: uat-tkgi-temr22-k8s-np-alex
  name: uat-tkgi-temr22-k8s-np-alex
  namespace: hrns-delegate1-dev-dade1fb84
spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      harness.io/name: uat-tkgi-temr22-k8s-np-alex
  serviceName: ""
  template:
    metadata:
      labels:
        harness.io/name: uat-tkgi-temr22-k8s-np-alex
    spec:
      imagePullSecrets:
      - name: hrns-cred
      serviceAccountName: hrns-sa
      containers:
      - image: wfcr-proxy-a.wellsfargo.net/docker-virtual/harness/delegate:latest
        imagePullPolicy: Always
        name: harness-delegate-instance
        ports:
          - containerPort: 8080
        lifecycle:
          postStart:
            exec:
              command:
                - bash
                - -c
                - cp /var/certs/cacerts jdk8u242-b08-jre/lib/security/cacerts
        resources:
          limits:
            cpu: "0.5"
            memory: "2048Mi"
          requests:
            cpu: "0.5"
            memory: "2048Mi"
        volumeMounts:
          - mountPath: /var/certs
            name: ca-bundle
        readinessProbe:
          exec:
            command:
              - test
              - -s
              - delegate.log
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - bash
              - -c
              - '[[ -e /opt/harness-delegate/msg/data/watcher-data && $(($(date +%s000) - $(grep heartbeat /opt/harness-delegate/msg/data/watcher-data | cut -d ":" -f 2 | cut -d "," -f 1))) -lt 300000 ]]'
          initialDelaySeconds: 240
          periodSeconds: 10
          failureThreshold: 2
          successThreshold: 1
          timeoutSeconds: 10
        env:
        - name: SCM_SKIP_SSL
          value: "true"
        - name: JAVA_OPTS
          value: "-Xms64M"
        - name: ACCOUNT_ID
          value: M6_xxR95RdiUcHu6wHkY_g
        - name: ACCOUNT_SECRET
          value: 3ea849a3049e422258937ce58b3fb36b
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io/gratis
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: uat-tkgi-temr22-k8s-np-alex
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: PROXY_HOST
          value: "proxy.wellsfargo.com"
        - name: PROXY_PORT
          value: "8080"
        - name: PROXY_SCHEME
          value: "http"
        - name: NO_PROXY
          value: "localhost,127.0.0.1,22.49.68.77,10.100.200.1,.wellsfargo.net,.wellsfargo.com,.privatelink.southcentralus.azmk8s.io,.azurecr.io"
        - name: PROXY_MANAGER
          value: "false"
        - name: POLL_FOR_TASKS
          value: "true"
        - name: ENABLE_CE
          value: "false"
        - name: GRPC_SERVICE_ENABLED
          value: "true"
        - name: GRPC_SERVICE_CONNECTOR_PORT
          value: "8080"
        - name: VERSION_CHECK_DISABLED
          value: "false"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_TAGS
          value: "provider: tkgi, zone: temr22, kind: k8s, env: np, rel: latest, ns: hrns-delegate1-dev-dade1fb84"
        - name: DELEGATE_ORG_IDENTIFIER
          value: ""
        - name: DELEGATE_PROJECT_IDENTIFIER
          value: ""
        - name: INIT_SCRIPT
          value: "echo install github cert\nopenssl s_client -connect github.wellsfargo.com:443
            -showcerts </dev/null 2>/dev/null | tee /usr/local/share/ca-certificates/github.crt
            >/dev/null && update-ca-certificates\necho github.wellsfargo.com cert installed\nmkdir
            -m 777 -p client-tools/scm/3ac4cefa/linux/amd64/ && curl -ks -L -x http://proxy.wellsfargo.com:8080
            -o client-tools/scm/3ac4cefa/linux/amd64/scm https://app.harness.io/public/shared/tools/scm/release/3ac4cefa/bin/linux/amd64/scm
            && chmod +x client-tools/scm/3ac4cefa/linux/amd64/scm\nls -al client-tools/scm/3ac4cefa/linux/amd64/scm\necho
            scm installed\t"
        - name: NEXT_GEN
          value: "true"
        - name: WATCHER_STORAGE_URL
          value: https://app.harness.io/public/free/freemium/watchers
        - name: WATCHER_CHECK_LOCATION
          value: current.version
        - name: REMOTE_WATCHER_URL_CDN
          value: https://app.harness.io/public/shared/watchers/builds
        - name: DELEGATE_STORAGE_URL
          value: https://app.harness.io
        - name: DELEGATE_CHECK_LOCATION
          value: delegatefree.txt
        - name: HELM_DESIRED_VERSION
          value: ""
        - name: USE_CDN
          value: "true"
        - name: CDN_URL
          value: https://app.harness.io
        - name: JRE_VERSION
          value: 1.8.0_242
        - name: HELM3_PATH
          value: ""
        - name: HELM_PATH
          value: ""
        - name: KUSTOMIZE_PATH
          value: ""
        - name: KUBECTL_PATH
          value: ""
      restartPolicy: Always
      volumes:
      - name: ca-bundle
        configMap:
          name: ca-bundle
---

apiVersion: v1
kind: Service
metadata:
  name: uat-tkgi-temr22-k8s-np-alex-svc
  namespace: hrns-delegate1-dev-dade1fb84
spec:
  type: ClusterIP
  selector:
    harness.io/name: uat-tkgi-temr22-k8s-np-alex
  ports:
    - port: 8080

