harnessApiVersion: '1.0'
type: APPLICATION_MANIFEST
gitFileConfig:
  branch: main
  connectorName: tmp-dev-frealmyr
  filePath: k8s/test/adguard
  useBranch: true
  useInlineServiceDefinition: false
storeType: HelmSourceRepo
